---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# WiNS Starting Kit with Networks

In this repository you will find useful resources for Women in Network Sciences (WiNS), as a Starting Kit with Networks.  

**Repository maintain by Postgraduate Committe of WiNS council**. If you would like to add information, or suggest some changes, please contact Francisca Ortiz (Postgraduate rep) by email: **franortizruiz@gmail.com**. 

Another repository that may be interesting for you, it is the one created with information for [postgraduates Women in Network Science](https://github.com/FranciscaOrtizRuiz/wins_postgraduate)

## Books, articles and places where to start learning about networks 🌻

Next, you will find different types of resources that you could use to learn from the basics until the advances of Networks. 

**Books**


**Articles**


**Places where to learn about Networks**

[Educational programmes recommended by NetSci](https://netscisociety.net/education)

[Graduate programmes recommended by INSNA](https://www.insna.org/graduate-programs)

[Workshops recommended by INSNA](https://www.insna.org/events/)

## Softwares

There are many softwares created for data collection and analysis of those networks. Here, we leave a list of some of them:

[Python - Programming language](https://www.python.org)

[R - Free software environment for statistical computing and graphics](https://www.r-project.org)

[R Studio - Free and open-source software for data science](https://www.rstudio.com)

[Vennmaker - An Actor-Centered Interative Network Mapping Tool](https://www.vennmaker.com/?lang=en)

[Canvas - Software for personal networks](https://www.networkcanvas.com)

[EgoNets - Software for personal networks](https://sourceforge.net/projects/egonet/)

[Visone - Visual Social Networks](https://visone.ethz.ch)

[Polinode - Collect, visualize and analyze connected data](https://www.polinode.com)

## International Organizations of Networks 💻

In the next international organizations, you can found useful information about their communities:

[WiNS - Women in Network Science](https://www.networkscienceinstitute.org/wins)

[INSNA - International Network for Social Network Analysis](https://www.insna.org)

[NETSCI - Network Science Society](https://netscisociety.net/home)

## Regional Organizations of Networks 💻

Some regional organizations working on networks, organized themselves every couple of year to have annual meetings and/or conferences. Probably worth looking at those closer to where are you currently based. 

[NASN - North American regional conference of the International Network for Social Network Analysis](https://twitter.com/nasocnet?lang=es)

[EUSN - European regional conferences of the International Network for Social Network Analysis](https://www.insna.org/events/-5th-european-conference-on-social-networks-eusn2021)

[ANSNA - Australian Network for Social Network Analysis of the International Network for Social Network Analysis](https://www.ansna.org.au/asnac2020-about)

[REDES - Iberoamerican Community of Networks](http://www.redes-sociales.net) 

## Journals about networks 💻

There are journals focusing in understand society, and many other aspects of the reality, from a networks approach. If you are interesting in a specific topic, maybe you can go to each journal website and see what they had already published about it: 

[Social Networks. An International Journal of Structural Analysis.](https://www.journals.elsevier.com/social-networks)

[Network Science](https://www.cambridge.org/core/journals/network-science)

[Connections. International Network for Social Network Analysis.](https://www.exeley.com/journal/connections)

[Journal of Social Structure International Network for Social Network Analysis](https://www.exeley.com/journal/journal_of_social_structure)

[REDES. Revista Hispana para el análisis de redes sociales.](https://revistes.uab.cat/redes/index)

## Twitter accounts to follow 📫 

The community of networks is very active in twitter. If you wan to know the most updated news, a good way is follow certain accounts, like:

[WiNS - Women in Network Sciences](https://twitter.com/WiNS_Society)

[NetSci - Network Science Society](https://twitter.com/netscisociety)

[INSNA - International Network for Social Network Analysis](https://twitter.com/SocNetAnalysts)

[Lista REDES - Iberoamerican community of Networks](https://twitter.com/lista_redes)

## Join the folowwing Listserv about Networks:

There are already a couple of Listserve around the community, in which you can subscribe to be update of the last advances in the field. In the next links, you can (un)subscribe yourself. 

[SOCNET - The Social Networks Listserv](https://www.insna.org/socnet)

[REDES - Iberoamerican network Listserv](http://www.redes-sociales.net): Click in "Forum" option to see the instructions for subscribe. 

## Other resources 🔭 

Other interesting resources that may be useful:

[RLadies - Community of women learning to code in R](https://rladies.org)

[YouTube Channel of WiNS - Videos of the seminar series](https://www.youtube.com/channel/UCJppCyVIY5_XsNOSl7mftRQ?view_as=subscriber)

[YouTube Channel of Lista Redes - Videos of seminar series and events (in spanish)](https://www.youtube.com/channel/UCofGv2fk2HnVXW45d1K4ujw/playlists)

[Networks in the Global World](http://ngw.spbu.ru)

[Knitting Networks Podcast](https://twitter.com/NetworksPodcast)


